BrowseBay/Controllers/BasketController.cs
using AutoMapper;
using BrowseBay.DataAccess;
using BrowseBay.Models;
using BrowseBay.Service.DTOs;
using BrowseBay.Service.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BrowseBay.Controllers
{
    public class BasketController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;
        private static BasketService _localBasket;
        public BasketController(
            AppDbContext context,
            UserManager<IdentityUser> userManager,
            IMapper mapper)
        {
            _unitOfWork = new UnitOfWork(context);
            _userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetCarts()
        {
            SyncDbBasketToLocalBasket();

            return _localBasket.GetNoOfItems() > 0 ?
                PartialView("BasketSummaryPartialView", _localBasket) :
                PartialView("NoContentPartialView");
        }

        [HttpGet]
        public IActionResult ToggleEditMode(bool onEditMode, bool save)
        {
            _localBasket.OnEditMode = onEditMode;

            if (save)
            {
                // sync the local basket to the database basket
                if (!onEditMode && !SyncLocalBasketToDbBasket())
                {
                    return BadRequest();
                }
            }
            else
            {
                // resyncs the database basket to the local basket
                return RedirectToAction("getcarts");
            }

            return _localBasket.GetNoOfItems() > 0 ?
                PartialView("BasketSummaryPartialView", _localBasket) :
                PartialView("NoContentPartialView");
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            _localBasket.Clear();

            if (!SyncLocalBasketToDbBasket())
            {
                return BadRequest();
            }
            else
            {
                return PartialView("NoContentPartialView");
            }
        }

        [HttpGet]
        public IActionResult ChangeCount(int id, int count)
        {
            _localBasket.ChangePurchaseCount(id, count);

            return PartialView("BasketSummaryPartialView", _localBasket);
        }

        /// <summary>
        /// Gets the local basket and syncs into the database basket
        /// </summary>
        /// <returns></returns>
        private bool SyncLocalBasketToDbBasket()
        {
            string? userId = _userManager.GetUserId(User);

            if (string.IsNullOrEmpty(userId))
            {
                return false;
            }

            return MergeDbBasketWithLocalBasket(userId);
        }

        /// <summary>
        /// Merge the local basket to database basket
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        private bool MergeDbBasketWithLocalBasket(string userId)
        {
            IEnumerable<Purchase> oldBasket = _unitOfWork.PurchaseManager.Get(c => c.OwnerId == userId);

            foreach (var purchase in oldBasket)
            {
                _unitOfWork.PurchaseManager.Delete(purchase);
            }

            return AddLocalBasketToDb();
        }

        /// <summary>
        /// Sets the local basket to database
        /// </summary>
        /// <returns></returns>
        private bool AddLocalBasketToDb()
        {
            IEnumerable<Purchase> newPurchase = _mapper.Map<IEnumerable<Purchase>>(_localBasket.GetBasket());

            foreach (var purchase in newPurchase)
            {
                purchase.Product = default!;
                _unitOfWork.PurchaseManager.Insert(purchase);
            }

            _unitOfWork.Save();
            return true;
        }

        /// <summary>
        /// Gets the database basket and syncs into the local basket
        /// </summary>
        /// <returns></returns>
        private bool SyncDbBasketToLocalBasket()
        {
            _localBasket = new BasketService();

            string? userId = _userManager.GetUserId(User);

            if (string.IsNullOrEmpty(userId))
            {
                return false;
            }

            IEnumerable<Purchase> purchases = _unitOfWork.PurchaseManager.Get(c => c.OwnerId == userId);

            _localBasket.AddNewBasket(_mapper.Map<IEnumerable<PurchaseReadDto>>(purchases));
            return true;
        }
    }
}

BrowseBay/Controllers/CategoryController.cs
using AutoMapper;
using BrowseBay.DataAccess;
using BrowseBay.Models;
using BrowseBay.Service;
using BrowseBay.Service.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace BrowseBay.Controllers
{
    [Authorize(Policy = nameof(Policy.AdminRights))]
    public class CategoryController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public CategoryController(
            AppDbContext context,
            IMapper mapper)
        {
            _unitOfWork = new UnitOfWork(context);
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _unitOfWork.CategoryManager.Get();

            return View(_mapper.Map<IEnumerable<CategoryReadDto>>(categories));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CategoryCreateDto model)
        {
            Category catModel = _mapper.Map<Category>(model);

            // check if the category name is already existing
            bool isUnique = IsUnique(catModel);

            if (!isUnique)
            {
                ModelState.AddModelError(nameof(model.Name), "A category with this name already exists.");
                return View();
            }

            _unitOfWork.CategoryManager.Insert(catModel);
            _unitOfWork.Save();

            TempData["success"] = "New category added.";
            return RedirectToAction("index", "category");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Category? category = _unitOfWork.CategoryManager.Find(id);

            if (category is null)
            {
                return NotFound();
            }

            return View(_mapper.Map<CategoryDto>(category));
        }

        [HttpPost]
        public IActionResult Edit(CategoryDto model)
        {
            Category catModel = _mapper.Map<Category>(model);

            // check if the category name is already existing
            bool isUnique = IsUnique(catModel, c => c.Id != catModel.Id);

            if (!isUnique)
            {
                ModelState.AddModelError(nameof(model.Name), "A category with this name already exists.");
                return View();
            }

            _unitOfWork.CategoryManager.Update(_mapper.Map<Category>(model));
            _unitOfWork.Save();

            TempData["success"] = "Product successfully changed.";
            return RedirectToAction("index", "category");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Category? category = _unitOfWork.CategoryManager.Find(id);

            if (category is null)
            {
                return NotFound();
            }

            _unitOfWork.CategoryManager.Delete(id);
            _unitOfWork.Save();

            TempData["success"] = "Category deleted.";
            return RedirectToAction("index", "category");
        }

        /// <summary>
        /// Checks if the normalized name of <paramref name="newCategory"/> already exists in the database
        /// </summary>
        /// <param name="newCategory"></param>
        /// <param name="expression"></param>
        /// <returns><c>true</c> if unique. Otherwise, <c>false</c></returns>
        private bool IsUnique(Category newCategory, Expression<Func<Category, bool>>? expression = null)
        {
            return !_unitOfWork.CategoryManager
                .Get(expression)
                .Any(c => c.NormalizedString.Equals(newCategory.NormalizedString));
        }
    }
}

BrowseBay/Controllers/ProductController.cs
using AutoMapper;
using BrowseBay.DataAccess;
using BrowseBay.Models;
using BrowseBay.Service;
using BrowseBay.Service.DTOs;
using BrowseBay.Service.Services;
using BrowseBay.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace BrowseBay.Controllers
{
    public class ProductController : Controller
    {
        private static CategoryStateManager _categoryStateManager;
        private readonly IUploadService<IFormFile> _uploadService;
        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;

        public ProductController(
            AppDbContext context,
            UserManager<IdentityUser> userManager,
            IUploadService<IFormFile> uploadService,
            IMapper mapper)
        {
            _unitOfWork = new UnitOfWork(context);
            _userManager = userManager;
            _uploadService = uploadService;
            _mapper = mapper;
        }

        [HttpPost]
        [Authorize(Policy = nameof(Policy.BuyerRights))]
        public IActionResult ViewProduct(int id)
        {
            Product? product = _unitOfWork.ProductManager.Find(id);

            if (product is null)
            {
                return NotFound();
            }

            return View(_mapper.Map<ProductReadDto>(product));
        }

        [HttpGet]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult Add(ProductCreateDto model)
        {
            // save product to database
            EntityEntry<Product> entityEntry = _unitOfWork.ProductManager.Insert(_mapper.Map<Product>(model));
            _unitOfWork.Save();

            // save product categories to database
            if (_categoryStateManager.Any())
            {
                int id = entityEntry.Entity.Id;
                IEnumerable<ProductCategoryDto> newCategoryDtos = _categoryStateManager.ToProductCategoryDtos(id);

                foreach (var dto in newCategoryDtos)
                {
                    ProductCategory newProductCategory = _mapper.Map<ProductCategory>(dto);
                    _unitOfWork.ProductCategoryManager.Insert(newProductCategory);
                }
            }

            _categoryStateManager.Clear();
            _unitOfWork.Save();

            TempData["success"] = "Product added successfully";
            return RedirectToAction("index", "home");
        }

        [HttpGet]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult Edit(int id)
        {
            Product? product = _unitOfWork.ProductManager.Find(id);

            if (product is null)
            {
                return NotFound();
            }

            return View(_mapper.Map<ProductDto>(product));
        }

        [HttpPost]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult Edit(ProductDto model)
        {
            _unitOfWork.ProductManager.Update(_mapper.Map<Product>(model));

            IEnumerable<ProductCategory> toDelete = _unitOfWork.ProductCategoryManager
                .Get(c => c.ProductId == model.Id);
            IEnumerable<ProductCategoryDto> toAdd = _categoryStateManager.ToProductCategoryDtos(model.Id);

            // delete the old categories of the product
            foreach (var delete in toDelete)
            {
                _unitOfWork.ProductCategoryManager.Delete(delete);
            }

            // replace with the new categories
            foreach (var add in toAdd)
            {
                _unitOfWork.ProductCategoryManager.Insert(_mapper.Map<ProductCategory>(add));
            }

            _unitOfWork.Save();

            TempData["success"] = "Product successfully updated";
            return RedirectToAction("index", "home");
        }

        [HttpPost]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult Delete(int id)
        {
            _unitOfWork.ProductManager.Delete(id);
            _unitOfWork.Save();

            TempData["success"] = "Product deleted";
            return RedirectToAction("index", "home");
        }

        [HttpPost]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public async Task<IActionResult> SetImage(IFormFile file)
        {
            string finalizedFileName = _uploadService.GetAvailableFileName(file.FileName);

            if (!await _uploadService.Upload(file))
            {
                return BadRequest("Please select a correct image format.");
            }

            return Content($"~/images/{finalizedFileName}");
        }

        [HttpGet, HttpPost]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult GetCategories(int id)
        {
            IEnumerable<Category> categories = _unitOfWork.CategoryManager.Get();

            var builder = new CategoryStateManagerBuilder();

            builder = builder
                .SetItems(_mapper.Map<IEnumerable<CategoryReadDto>>(categories));

            // obtain the categories of the product with the specified id
            if (id > 0)
            {
                IEnumerable<ProductCategory> productCategories = _unitOfWork.ProductCategoryManager
                    .Get(c => c.ProductId == id);

                builder = builder.SetSelectedItems(productCategories.Select(c => c.CategoryId));
            }

            _categoryStateManager = builder.Build();

            return PartialView("CategoryTogglePartialView", _categoryStateManager);
        }

        [HttpGet]
        [Authorize(Policy = nameof(Policy.BuyerRights))]
        public IActionResult AddToCart(int id)
        {
            string? userId = _userManager.GetUserId(User);

            Product? product = _unitOfWork.ProductManager.Find(id);

            if (product is null || string.IsNullOrEmpty(userId))
            {
                return NotFound();
            }

            Purchase? purchase = _unitOfWork.PurchaseManager.Get(c => c.OwnerId == userId && c.ProductId == id).FirstOrDefault();

            if (purchase is null)
            {
                purchase = new Purchase
                {
                    OwnerId = userId,
                    ProductId = product.Id,
                    Quantity = 1,
                };

                _unitOfWork.PurchaseManager.Insert(purchase);
            }
            else
            {
                purchase.Quantity++;
                _unitOfWork.PurchaseManager.Update(purchase);
            }

            _unitOfWork.Save();

            return Ok(product.Name);
        }

        [HttpGet]
        [Authorize(Policy = nameof(Policy.SellerRights))]
        public IActionResult ToggleCategory(int id)
        {
            _categoryStateManager.Toggle(id);

            return PartialView("CategoryTogglePartialView", _categoryStateManager);
        }
    }
}

BrowseBay/Views/Shared/_Layout.cshtml
@inject IAuthorizationService authService
@inject IAccountService accountService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BrowseBay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/BrowseBay.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (await accountService.IsSignedIn(User))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BrowseBay</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Shop</a>
                            </li>
                            @if ((await authService.AuthorizeAsync(User, nameof(Policy.SellerRights))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Add">Add Product</a>
                                </li>
                            }
                            @if ((await authService.AuthorizeAsync(User, nameof(Policy.AdminRights))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                </li>
                            }
                        </ul>
                    </div>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">
                                    <i class="bi bi-box-arrow-right"></i> Logout @User.Identity?.Name
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">
                                    <i class="bi bi-basket"></i>
                                    <span class="d-sm-none"> View Cart</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BrowseBay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BrowseBay/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}